import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Footer from '../bin/components/footer';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Deal Cte</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Deal Cte</h1>

        <Link href="/tables">
          <button className={styles.tableButton} >Procurar por mesas</button>
        </Link>
      </main>

      <Footer />
    </div>
  )
}

export default Home
